server:
  port: 8082

spring:
  # 测试环境使用mybatis
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  #redis
  redis:
    #redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    pool:
      # 连接池最大连接数(使用负值表示没有限制)
      max-active: 8
      # 连接池最大阻塞等待时间，（使用负值表示没有限制）
      max-wait: -1
      # 连接池中最大空闲连接
      max-idle: 8
      # 连接池中最小空闲连接
      min-idle: 0
      # 连接超时时间
      timeout: 0


#指定mybatis映射文件的地址
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# mybatis分页插件
pagehelper:
  helper-dialect: mysql
  reasonable: "true"
  support-methods-arguments: "true"
  params: count=countSql

logging:
  level:
    root: INFO



