spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sc?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  data:
    elasticsearch:
      cluster-name: es
      # 配置文件中的端口是9200：是通过http连接的端口，9300是TCP连接的端口
      cluster-nodes: localhost:9300
